apiVersion: v2
name: litellm-platform
description: LLM Ops - Frontend + Backend + Worker
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: litellm-helm
    version: ">=1.0.0"
    repository: "file://../../../litellm/deploy/charts/litellm-helm"
    condition: litellm.enabled
