{{- if and .Values.ingress.enabled .Values.frontend.enabled .Values.ingress.frontend.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "litellm-platform.fullname" . }}-frontend
  labels:
    app.kubernetes.io/component: frontend
    {{- include "litellm-platform.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.frontend.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.frontend.path | quote }}
            pathType: {{ .Values.ingress.frontend.pathType }}
            backend:
              service:
                name: {{ include "litellm-platform.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}
{{- if and .Values.ingress.enabled .Values.frontend.enabled .Values.ingress.frontend.enabled .Values.backend.enabled .Values.ingress.backend.enabled }}
---
{{- end }}
{{- if and .Values.ingress.enabled .Values.backend.enabled .Values.ingress.backend.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "litellm-platform.fullname" . }}-backend
  labels:
    app.kubernetes.io/component: backend
    {{- include "litellm-platform.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.backend.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.backend.path | quote }}
            pathType: {{ .Values.ingress.backend.pathType }}
            backend:
              service:
                name: {{ include "litellm-platform.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
{{- end }}
